// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    /// <summary>
    /// List of custom property values for an organization
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomPropertiesForOrgsGetEnterprisePropertyValues : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The organization_id property</summary>
        public int? OrganizationId { get; set; }
        /// <summary>The organization_login property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganizationLogin { get; set; }
#nullable restore
#else
        public string OrganizationLogin { get; set; }
#endif
        /// <summary>List of custom property names and associated values</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.EnterpriseCloud.Models.CustomPropertyValue>? Properties { get; set; }
#nullable restore
#else
        public List<global::GitHub.EnterpriseCloud.Models.CustomPropertyValue> Properties { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Models.CustomPropertiesForOrgsGetEnterprisePropertyValues"/> and sets the default values.
        /// </summary>
        public CustomPropertiesForOrgsGetEnterprisePropertyValues()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Models.CustomPropertiesForOrgsGetEnterprisePropertyValues"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Models.CustomPropertiesForOrgsGetEnterprisePropertyValues CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Models.CustomPropertiesForOrgsGetEnterprisePropertyValues();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "organization_id", n => { OrganizationId = n.GetIntValue(); } },
                { "organization_login", n => { OrganizationLogin = n.GetStringValue(); } },
                { "properties", n => { Properties = n.GetCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.CustomPropertyValue>(global::GitHub.EnterpriseCloud.Models.CustomPropertyValue.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("organization_id", OrganizationId);
            writer.WriteStringValue("organization_login", OrganizationLogin);
            writer.WriteCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.CustomPropertyValue>("properties", Properties);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
