// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnterpriseTokenInventoryItem_credential_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "classic_pat")]
        #pragma warning disable CS1591
        Classic_pat,
        #pragma warning restore CS1591
        [EnumMember(Value = "oauth_app_user_token")]
        #pragma warning disable CS1591
        Oauth_app_user_token,
        #pragma warning restore CS1591
        [EnumMember(Value = "github_app_user_token")]
        #pragma warning disable CS1591
        Github_app_user_token,
        #pragma warning restore CS1591
        [EnumMember(Value = "fine_grained_pat")]
        #pragma warning disable CS1591
        Fine_grained_pat,
        #pragma warning restore CS1591
        [EnumMember(Value = "ssh_key")]
        #pragma warning disable CS1591
        Ssh_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "github_app_installation")]
        #pragma warning disable CS1591
        Github_app_installation,
        #pragma warning restore CS1591
        [EnumMember(Value = "federated_jti")]
        #pragma warning disable CS1591
        Federated_jti,
        #pragma warning restore CS1591
    }
}
