// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnterpriseTokenInventoryItem_authorization_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "currently_authorized")]
        #pragma warning disable CS1591
        Currently_authorized,
        #pragma warning restore CS1591
        [EnumMember(Value = "member_owned_only")]
        #pragma warning disable CS1591
        Member_owned_only,
        #pragma warning restore CS1591
    }
}
