// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnterpriseTokenInventoryItem_effective_access_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "effective")]
        #pragma warning disable CS1591
        Effective,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_effective")]
        #pragma warning disable CS1591
        Not_effective,
        #pragma warning restore CS1591
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
    }
}
