// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    /// <summary>Source answers the question, &quot;where did this role come from?&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnterpriseRole_source
    {
        [EnumMember(Value = "Enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
        [EnumMember(Value = "Predefined")]
        #pragma warning disable CS1591
        Predefined,
        #pragma warning restore CS1591
    }
}
