// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    /// <summary>Who can edit the values of the property.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrganizationCustomPropertyPayload_values_editable_by
    {
        [EnumMember(Value = "enterprise_actors")]
        #pragma warning disable CS1591
        Enterprise_actors,
        #pragma warning restore CS1591
        [EnumMember(Value = "enterprise_and_org_actors")]
        #pragma warning disable CS1591
        Enterprise_and_org_actors,
        #pragma warning restore CS1591
    }
}
