// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    /// <summary>The type of usage report to generate</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UsageReportExportRequest_report_type
    {
        [EnumMember(Value = "detailed")]
        #pragma warning disable CS1591
        Detailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "summarized")]
        #pragma warning disable CS1591
        Summarized,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium_request")]
        #pragma warning disable CS1591
        Premium_request,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_credit")]
        #pragma warning disable CS1591
        Ai_credit,
        #pragma warning restore CS1591
    }
}
