// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsageReportExport : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The login of the user who requested the export</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Actor { get; set; }
#nullable restore
#else
        public string Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the report export was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>URLs to download the completed report. Only present when the report status is `completed`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DownloadUrls { get; set; }
#nullable restore
#else
        public List<string> DownloadUrls { get; set; }
#endif
        /// <summary>The end date for the report</summary>
        public Date? EndDate { get; set; }
        /// <summary>Unique identifier for the usage report export</summary>
        public Guid? Id { get; set; }
        /// <summary>The type of usage report</summary>
        public global::GitHub.EnterpriseCloud.Models.UsageReportExport_report_type? ReportType { get; set; }
        /// <summary>The start date for the report</summary>
        public Date? StartDate { get; set; }
        /// <summary>The current status of the report export</summary>
        public global::GitHub.EnterpriseCloud.Models.UsageReportExport_status? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Models.UsageReportExport"/> and sets the default values.
        /// </summary>
        public UsageReportExport()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Models.UsageReportExport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Models.UsageReportExport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Models.UsageReportExport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor", n => { Actor = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "download_urls", n => { DownloadUrls = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "report_type", n => { ReportType = n.GetEnumValue<global::GitHub.EnterpriseCloud.Models.UsageReportExport_report_type>(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::GitHub.EnterpriseCloud.Models.UsageReportExport_status>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("actor", Actor);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfPrimitiveValues<string>("download_urls", DownloadUrls);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteGuidValue("id", Id);
            writer.WriteEnumValue<global::GitHub.EnterpriseCloud.Models.UsageReportExport_report_type>("report_type", ReportType);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteEnumValue<global::GitHub.EnterpriseCloud.Models.UsageReportExport_status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
