// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Disable;
using GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Enable;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\access-restrictions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccessRestrictionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The disable property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Disable.DisableRequestBuilder Disable
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Enable.EnableRequestBuilder Enable
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.AccessRestrictionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccessRestrictionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/access-restrictions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.AccessRestrictionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccessRestrictionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/access-restrictions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
