// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\innersource-vulnerabilities\sync\status\{job_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithJob_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJob_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities/sync/status/{job_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithJob_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities/sync/status/{job_id}", rawUrl)
        {
        }
        /// <summary>
        /// Get the status of an asynchronous innersource vulnerability sync operation for an enterprise.Returns 202 with a `Retry-After` header while the sync is still processing, or 200 withthe full sync results once complete.This endpoint does not support OAuth apps or personal access tokens.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/enterprise-admin/security-advisories#get-innersource-vulnerability-sync-status-for-an-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse?> GetAsWithJob_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse> GetAsWithJob_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the status of an asynchronous innersource vulnerability sync operation for an enterprise.Returns 202 with a `Retry-After` header while the sync is still processing, or 200 withthe full sync results once complete.This endpoint does not support OAuth apps or personal access tokens.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/enterprise-admin/security-advisories#get-innersource-vulnerability-sync-status-for-an-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsWithJob_GetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get the status of an asynchronous innersource vulnerability sync operation for an enterprise.Returns 202 with a `Retry-After` header while the sync is still processing, or 200 withthe full sync results once complete.This endpoint does not support OAuth apps or personal access tokens.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1"/>, <see cref="global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithJob_GetResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult? ExternalVulnerabilitySyncResult { get; set; }
#nullable restore
#else
            public global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult ExternalVulnerabilitySyncResult { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1? WithJobGetResponseMember1 { get; set; }
#nullable restore
#else
            public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1 WithJobGetResponseMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_GetResponse();
                if("external-vulnerability-sync-result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ExternalVulnerabilitySyncResult = new global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ExternalVulnerabilitySyncResult != null)
                {
                    return ExternalVulnerabilitySyncResult.GetFieldDeserializers();
                }
                else if(WithJobGetResponseMember1 != null)
                {
                    return WithJobGetResponseMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ExternalVulnerabilitySyncResult != null)
                {
                    writer.WriteObjectValue<global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult>(null, ExternalVulnerabilitySyncResult);
                }
                else if(WithJobGetResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1>(null, WithJobGetResponseMember1);
                }
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithJob_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1"/>, <see cref="global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithJob_Response : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult? ExternalVulnerabilitySyncResult { get; set; }
#nullable restore
#else
            public global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult ExternalVulnerabilitySyncResult { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1? WithJobGetResponseMember1 { get; set; }
#nullable restore
#else
            public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1 WithJobGetResponseMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder.WithJob_Response();
                if("external-vulnerability-sync-result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ExternalVulnerabilitySyncResult = new global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ExternalVulnerabilitySyncResult != null)
                {
                    return ExternalVulnerabilitySyncResult.GetFieldDeserializers();
                }
                else if(WithJobGetResponseMember1 != null)
                {
                    return WithJobGetResponseMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ExternalVulnerabilitySyncResult != null)
                {
                    writer.WriteObjectValue<global::GitHub.EnterpriseCloud.Models.ExternalVulnerabilitySyncResult>(null, ExternalVulnerabilitySyncResult);
                }
                else if(WithJobGetResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_GetResponseMember1>(null, WithJobGetResponseMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
