// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.Item;
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\visual-studio-subscriptions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VisualStudioSubscriptionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.visualStudioSubscriptions.item collection</summary>
        /// <param name="position">The ID of the Visual Studio subscription to add or update the match for. This is a GUID that comes from the Visual Studio management portal.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.Item.WithVisual_studio_subscription_ItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.Item.WithVisual_studio_subscription_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("visual_studio_subscription_id", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.Item.WithVisual_studio_subscription_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VisualStudioSubscriptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/visual-studio-subscriptions{?is_unmatched_only*,page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VisualStudioSubscriptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/visual-studio-subscriptions{?is_unmatched_only*,page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Retrieves a list of Visual Studio subscriptions for the specified enterprise.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/enterprise-admin/licensing#get-a-list-of-visual-studio-subscriptions-for-the-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsGetResponse?> GetAsVisualStudioSubscriptionsGetResponseAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsGetResponse> GetAsVisualStudioSubscriptionsGetResponseAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsGetResponse>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a list of Visual Studio subscriptions for the specified enterprise.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/enterprise-admin/licensing#get-a-list-of-visual-studio-subscriptions-for-the-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsVisualStudioSubscriptionsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsResponse?> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsResponse> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsResponse>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieves a list of Visual Studio subscriptions for the specified enterprise.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Retrieves a list of Visual Studio subscriptions for the specified enterprise.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VisualStudioSubscriptionsRequestBuilderGetQueryParameters 
        {
            /// <summary>When true, only returns Visual Studio subscriptions that are not matched to a GitHub user.</summary>
            [QueryParameter("is_unmatched_only")]
            public bool? IsUnmatchedOnly { get; set; }
            /// <summary>The page number of the results to fetch. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class VisualStudioSubscriptionsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder.VisualStudioSubscriptionsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
