// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.Dependabot.Item
{
    /// <summary>The reason for dismissing the alert.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithAlert_numberPostRequestBody_dismissed_reason
    {
        [EnumMember(Value = "fix_started")]
        #pragma warning disable CS1591
        Fix_started,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_bandwidth")]
        #pragma warning disable CS1591
        No_bandwidth,
        #pragma warning restore CS1591
        [EnumMember(Value = "tolerable_risk")]
        #pragma warning disable CS1591
        Tolerable_risk,
        #pragma warning restore CS1591
        [EnumMember(Value = "inaccurate")]
        #pragma warning disable CS1591
        Inaccurate,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_used")]
        #pragma warning disable CS1591
        Not_used,
        #pragma warning restore CS1591
    }
}
