// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.Item;
using GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeAll;
using GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeCredentialType;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\credential-authorizations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CredentialAuthorizationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The revokeAll property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeAll.RevokeAllRequestBuilder RevokeAll
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeAll.RevokeAllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The revokeCredentialType property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeCredentialType.RevokeCredentialTypeRequestBuilder RevokeCredentialType
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeCredentialType.RevokeCredentialTypeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.credentialAuthorizations.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.Item.WithUsernameItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.Item.WithUsernameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("username", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.Item.WithUsernameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.CredentialAuthorizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CredentialAuthorizationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/credential-authorizations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.CredentialAuthorizationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CredentialAuthorizationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/credential-authorizations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
