// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Billing;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Content_exclusion;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Metrics;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Policies;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.UsageRecords;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Copilot
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\copilot
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CopilotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The billing property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Billing.BillingRequestBuilder Billing
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Billing.BillingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The content_exclusion property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Content_exclusion.Content_exclusionRequestBuilder Content_exclusion
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Content_exclusion.Content_exclusionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customAgents property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder CustomAgents
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The policies property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Policies.PoliciesRequestBuilder Policies
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.Policies.PoliciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usageRecords property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.UsageRecords.UsageRecordsRequestBuilder UsageRecords
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.UsageRecords.UsageRecordsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CopilotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CopilotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
