// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Rulesets
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RulesetsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The actors that can bypass the rules in this ruleset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.EnterpriseCloud.Models.RepositoryRulesetBypassActor>? BypassActors { get; set; }
#nullable restore
#else
        public List<global::GitHub.EnterpriseCloud.Models.RepositoryRulesetBypassActor> BypassActors { get; set; }
#endif
        /// <summary>Conditions for an enterprise ruleset.The `conditions` object supports either of the following combinations: - `organization_id` and `repository_name` - `organization_id` and `repository_property` - `organization_name` and `repository_name` - `organization_name` and `repository_property` - `organization_property` and `repository_name` - `organization_property` and `repository_property`For branch and tag rulesets, the `conditions` object should also contain the `ref_name` property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.EnterpriseCloud.Models.EnterpriseRulesetConditions? Conditions { get; set; }
#nullable restore
#else
        public global::GitHub.EnterpriseCloud.Models.EnterpriseRulesetConditions Conditions { get; set; }
#endif
        /// <summary>The enforcement level of the ruleset. `evaluate` allows admins to test rules before enforcing them. Admins can view insights on the Rule Insights page. `evaluate` is not available for the `repository` target.</summary>
        public global::GitHub.EnterpriseCloud.Models.RepositoryRuleEnforcement? Enforcement { get; set; }
        /// <summary>The name of the ruleset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>An array of rules within the ruleset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.EnterpriseCloud.Models.EnterpriseRules>? Rules { get; set; }
#nullable restore
#else
        public List<global::GitHub.EnterpriseCloud.Models.EnterpriseRules> Rules { get; set; }
#endif
        /// <summary>The target of the ruleset</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody_target? Target { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody"/> and sets the default values.
        /// </summary>
        public RulesetsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            Target = global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody_target.Branch;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bypass_actors", n => { BypassActors = n.GetCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.RepositoryRulesetBypassActor>(global::GitHub.EnterpriseCloud.Models.RepositoryRulesetBypassActor.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conditions", n => { Conditions = n.GetObjectValue<global::GitHub.EnterpriseCloud.Models.EnterpriseRulesetConditions>(global::GitHub.EnterpriseCloud.Models.EnterpriseRulesetConditions.CreateFromDiscriminatorValue); } },
                { "enforcement", n => { Enforcement = n.GetEnumValue<global::GitHub.EnterpriseCloud.Models.RepositoryRuleEnforcement>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "rules", n => { Rules = n.GetCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.EnterpriseRules>(global::GitHub.EnterpriseCloud.Models.EnterpriseRules.CreateFromDiscriminatorValue)?.AsList(); } },
                { "target", n => { Target = n.GetEnumValue<global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody_target>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.RepositoryRulesetBypassActor>("bypass_actors", BypassActors);
            writer.WriteObjectValue<global::GitHub.EnterpriseCloud.Models.EnterpriseRulesetConditions>("conditions", Conditions);
            writer.WriteEnumValue<global::GitHub.EnterpriseCloud.Models.RepositoryRuleEnforcement>("enforcement", Enforcement);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Models.EnterpriseRules>("rules", Rules);
            writer.WriteEnumValue<global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsPostRequestBody_target>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
