// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\settings\billing\advanced-security
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdvancedSecurityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdvancedSecurityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing/advanced-security{?advanced_security_product*,page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdvancedSecurityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing/advanced-security{?advanced_security_product*,page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the GitHub Advanced Security active committers for an enterprise per repository. The authenticated user must be an enterprise admin or billing manager.Each distinct user login across all repositories is counted as a single Advanced Security seat, so the `total_advanced_security_committers` is not the sum of active_users for each repository.The total number of repositories with committer information is tracked by the `total_count` field.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/enterprise-admin/licensing#get-github-advanced-security-active-committers-for-an-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Models.AdvancedSecurityActiveCommitters"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Models.AdvancedSecurityActiveCommitters?> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder.AdvancedSecurityRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Models.AdvancedSecurityActiveCommitters> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder.AdvancedSecurityRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Models.AdvancedSecurityActiveCommitters>(requestInfo, global::GitHub.EnterpriseCloud.Models.AdvancedSecurityActiveCommitters.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the GitHub Advanced Security active committers for an enterprise per repository. The authenticated user must be an enterprise admin or billing manager.Each distinct user login across all repositories is counted as a single Advanced Security seat, so the `total_advanced_security_committers` is not the sum of active_users for each repository.The total number of repositories with committer information is tracked by the `total_count` field.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder.AdvancedSecurityRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder.AdvancedSecurityRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the GitHub Advanced Security active committers for an enterprise per repository. The authenticated user must be an enterprise admin or billing manager.Each distinct user login across all repositories is counted as a single Advanced Security seat, so the `total_advanced_security_committers` is not the sum of active_users for each repository.The total number of repositories with committer information is tracked by the `total_count` field.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdvancedSecurityRequestBuilderGetQueryParameters 
        {
            /// <summary>The security product to get GitHub Advanced Security active committers for.For standalone Code Scanning or Secret Protection products, this parameter is required to specify which product you want committer information for. For other plans this parameter cannot be used.</summary>
            [Obsolete("This property is deprecated, use AdvancedSecurityProductAsGetAdvancedSecurityProductQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("advanced_security_product")]
            public string? AdvancedSecurityProduct { get; set; }
#nullable restore
#else
            [QueryParameter("advanced_security_product")]
            public string AdvancedSecurityProduct { get; set; }
#endif
            /// <summary>The security product to get GitHub Advanced Security active committers for.For standalone Code Scanning or Secret Protection products, this parameter is required to specify which product you want committer information for. For other plans this parameter cannot be used.</summary>
            [QueryParameter("advanced_security_product")]
            public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.GetAdvanced_security_productQueryParameterType? AdvancedSecurityProductAsGetAdvancedSecurityProductQueryParameterType { get; set; }
            /// <summary>The page number of the results to fetch. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AdvancedSecurityRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.AdvancedSecurity.AdvancedSecurityRequestBuilder.AdvancedSecurityRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
