// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.RevokeCredentialType
{
    /// <summary>The type of credential to revoke across the enterprise.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RevokeCredentialTypePostRequestBody_credential_type
    {
        [EnumMember(Value = "classic_pat")]
        #pragma warning disable CS1591
        Classic_pat,
        #pragma warning restore CS1591
        [EnumMember(Value = "fine_grained_pat")]
        #pragma warning disable CS1591
        Fine_grained_pat,
        #pragma warning restore CS1591
        [EnumMember(Value = "ssh_key")]
        #pragma warning disable CS1591
        Ssh_key,
        #pragma warning restore CS1591
        [EnumMember(Value = "oauth_app_token")]
        #pragma warning disable CS1591
        Oauth_app_token,
        #pragma warning restore CS1591
    }
}
