// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SourcePutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to create a ruleset to protect agent definition files. Defaults to true.</summary>
        public bool? CreateRuleset { get; set; }
        /// <summary>The ID of the organization to use as the custom agents source.</summary>
        public int? OrganizationId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourcePutRequestBody"/> and sets the default values.
        /// </summary>
        public SourcePutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            CreateRuleset = true;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourcePutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourcePutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourcePutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "create_ruleset", n => { CreateRuleset = n.GetBoolValue(); } },
                { "organization_id", n => { OrganizationId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("create_ruleset", CreateRuleset);
            writer.WriteIntValue("organization_id", OrganizationId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
