// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\innersource-vulnerabilities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InnersourceVulnerabilitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The sync property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.SyncRequestBuilder Sync
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.InnersourceVulnerabilitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InnersourceVulnerabilitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.InnersourceVulnerabilitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InnersourceVulnerabilitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
