// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\enterprise-roles\teams
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TeamsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.enterpriseRoles.teams.item collection</summary>
        /// <param name="position">The slug of the enterprise team name.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.Item.WithTeam_slugItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.Item.WithTeam_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("team_slug", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.Item.WithTeam_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/enterprise-roles/teams", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.Teams.TeamsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TeamsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/enterprise-roles/teams", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
