// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source;
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\copilot\custom-agents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomAgentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The source property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourceRequestBuilder Source
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.Source.SourceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomAgentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot/custom-agents{?page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomAgentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/copilot/custom-agents{?page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the list of all custom agents defined in the /agents/*.md files in the .github-private repository for the enterprise.If no source repository has been configured, returns `null` for `custom_agents`.Enterprise owners with read access to AI Controls can use this endpoint.OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/copilot/copilot-custom-agents#get-custom-agents-for-an-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgents404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse?> GetAsCustomAgentsGetResponseAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse> GetAsCustomAgentsGetResponseAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgents404Error.CreateFromDiscriminatorValue },
                { "500", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the list of all custom agents defined in the /agents/*.md files in the .github-private repository for the enterprise.If no source repository has been configured, returns `null` for `custom_agents`.Enterprise owners with read access to AI Controls can use this endpoint.OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/copilot/copilot-custom-agents#get-custom-agents-for-an-enterprise" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgents404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsCustomAgentsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsResponse?> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsResponse> GetAsync(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgents404Error.CreateFromDiscriminatorValue },
                { "500", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsResponse>(requestInfo, global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the list of all custom agents defined in the /agents/*.md files in the .github-private repository for the enterprise.If no source repository has been configured, returns `null` for `custom_agents`.Enterprise owners with read access to AI Controls can use this endpoint.OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the list of all custom agents defined in the /agents/*.md files in the .github-private repository for the enterprise.If no source repository has been configured, returns `null` for `custom_agents`.Enterprise owners with read access to AI Controls can use this endpoint.OAuth app tokens and personal access tokens (classic) need the `admin:enterprise` scope to use this endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomAgentsRequestBuilderGetQueryParameters 
        {
            /// <summary>The page number of the results to fetch. For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of results per page (max 100). For more information, see &quot;[Using pagination in the REST API](https://docs.github.com/enterprise-cloud@latest/rest/using-the-rest-api/using-pagination-in-the-rest-api).&quot;</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CustomAgentsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsRequestBuilder.CustomAgentsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
