// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomAgentsGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of custom agents defined in the repository. Returns `null` if no source repository is configured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse_custom_agents>? CustomAgents { get; set; }
#nullable restore
#else
        public List<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse_custom_agents> CustomAgents { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse"/> and sets the default values.
        /// </summary>
        public CustomAgentsGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_agents", n => { CustomAgents = n.GetCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse_custom_agents>(global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse_custom_agents.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CustomAgents.CustomAgentsGetResponse_custom_agents>("custom_agents", CustomAgents);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
