// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions;
using GitHub.EnterpriseCloud.Enterprises.Item.Actions;
using GitHub.EnterpriseCloud.Enterprises.Item.Announcement;
using GitHub.EnterpriseCloud.Enterprises.Item.Apps;
using GitHub.EnterpriseCloud.Enterprises.Item.AuditLog;
using GitHub.EnterpriseCloud.Enterprises.Item.BypassRequests;
using GitHub.EnterpriseCloud.Enterprises.Item.CodeScanning;
using GitHub.EnterpriseCloud.Enterprises.Item.CodeSecurity;
using GitHub.EnterpriseCloud.Enterprises.Item.Code_security_and_analysis;
using GitHub.EnterpriseCloud.Enterprises.Item.ConsumedLicenses;
using GitHub.EnterpriseCloud.Enterprises.Item.Copilot;
using GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations;
using GitHub.EnterpriseCloud.Enterprises.Item.Dependabot;
using GitHub.EnterpriseCloud.Enterprises.Item.DismissalRequests;
using GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles;
using GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities;
using GitHub.EnterpriseCloud.Enterprises.Item.Installation;
using GitHub.EnterpriseCloud.Enterprises.Item.Item;
using GitHub.EnterpriseCloud.Enterprises.Item.LicenseSyncStatus;
using GitHub.EnterpriseCloud.Enterprises.Item.Members;
using GitHub.EnterpriseCloud.Enterprises.Item.NetworkConfigurations;
using GitHub.EnterpriseCloud.Enterprises.Item.NetworkSettings;
using GitHub.EnterpriseCloud.Enterprises.Item.OrgProperties;
using GitHub.EnterpriseCloud.Enterprises.Item.Properties;
using GitHub.EnterpriseCloud.Enterprises.Item.Rulesets;
using GitHub.EnterpriseCloud.Enterprises.Item.SecretScanning;
using GitHub.EnterpriseCloud.Enterprises.Item.Settings;
using GitHub.EnterpriseCloud.Enterprises.Item.Teams;
using GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithEnterpriseItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accessRestrictions property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.AccessRestrictionsRequestBuilder AccessRestrictions
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.AccessRestrictions.AccessRestrictionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The actions property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Actions.ActionsRequestBuilder Actions
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The announcement property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Announcement.AnnouncementRequestBuilder Announcement
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Announcement.AnnouncementRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apps property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.AppsRequestBuilder Apps
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.AppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auditLog property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.AuditLog.AuditLogRequestBuilder AuditLog
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.AuditLog.AuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bypassRequests property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.BypassRequests.BypassRequestsRequestBuilder BypassRequests
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.BypassRequests.BypassRequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The code_security_and_analysis property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Code_security_and_analysis.Code_security_and_analysisRequestBuilder Code_security_and_analysis
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Code_security_and_analysis.Code_security_and_analysisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codeScanning property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CodeScanning.CodeScanningRequestBuilder CodeScanning
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.CodeScanning.CodeScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codeSecurity property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CodeSecurity.CodeSecurityRequestBuilder CodeSecurity
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.CodeSecurity.CodeSecurityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The consumedLicenses property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.ConsumedLicenses.ConsumedLicensesRequestBuilder ConsumedLicenses
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.ConsumedLicenses.ConsumedLicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The copilot property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CopilotRequestBuilder Copilot
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Copilot.CopilotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentialAuthorizations property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.CredentialAuthorizationsRequestBuilder CredentialAuthorizations
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.CredentialAuthorizations.CredentialAuthorizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dependabot property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Dependabot.DependabotRequestBuilder Dependabot
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Dependabot.DependabotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dismissalRequests property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.DismissalRequests.DismissalRequestsRequestBuilder DismissalRequests
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.DismissalRequests.DismissalRequestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enterpriseRoles property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.EnterpriseRolesRequestBuilder EnterpriseRoles
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.EnterpriseRoles.EnterpriseRolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The innersourceVulnerabilities property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.InnersourceVulnerabilitiesRequestBuilder InnersourceVulnerabilities
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.InnersourceVulnerabilitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installation property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Installation.InstallationRequestBuilder Installation
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Installation.InstallationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenseSyncStatus property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.LicenseSyncStatus.LicenseSyncStatusRequestBuilder LicenseSyncStatus
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.LicenseSyncStatus.LicenseSyncStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Members.MembersRequestBuilder Members
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The networkConfigurations property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.NetworkConfigurations.NetworkConfigurationsRequestBuilder NetworkConfigurations
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.NetworkConfigurations.NetworkConfigurationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The networkSettings property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.NetworkSettings.NetworkSettingsRequestBuilder NetworkSettings
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.NetworkSettings.NetworkSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgProperties property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.OrgProperties.OrgPropertiesRequestBuilder OrgProperties
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.OrgProperties.OrgPropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The properties property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Properties.PropertiesRequestBuilder Properties
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Properties.PropertiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rulesets property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsRequestBuilder Rulesets
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Rulesets.RulesetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secretScanning property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.SecretScanning.SecretScanningRequestBuilder SecretScanning
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.SecretScanning.SecretScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The visualStudioSubscriptions property</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder VisualStudioSubscriptions
        {
            get => new global::GitHub.EnterpriseCloud.Enterprises.Item.VisualStudioSubscriptions.VisualStudioSubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.item collection</summary>
        /// <param name="position">The security feature to enable or disable.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("security_product", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.Item.WithSecurity_productItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.WithEnterpriseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterpriseItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.WithEnterpriseItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithEnterpriseItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
