// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item.Logs;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\actions\jobs\{job_id}\steps\{step_number}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithStep_numberItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The logs property</summary>
        public global::GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item.Logs.LogsRequestBuilder Logs
        {
            get => new global::GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item.Logs.LogsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item.WithStep_numberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStep_numberItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/actions/jobs/{job_id}/steps/{step_number}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Repos.Item.Item.Actions.Jobs.Item.Steps.Item.WithStep_numberItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithStep_numberItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/actions/jobs/{job_id}/steps/{step_number}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
