// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InstallationsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Client ID of the GitHub App to install.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The names of the repositories to which the installation will be granted access. This is the simple name of the repository, not the full name (e.g., `hello-world` not `octocat/hello-world`). This is only required when `repository_selection` is `selected`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Repositories { get; set; }
#nullable restore
#else
        public List<string> Repositories { get; set; }
#endif
        /// <summary>The repository selection for the GitHub App. Must be one of:* `all` - the installation can access all repositories in the organization.* `selected` - the installation can access only the listed repositories.* `none` - no repository permissions are requested. Only use when the app does not request repository permissions.</summary>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody_repository_selection? RepositorySelection { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody"/> and sets the default values.
        /// </summary>
        public InstallationsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "repositories", n => { Repositories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "repository_selection", n => { RepositorySelection = n.GetEnumValue<global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody_repository_selection>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteCollectionOfPrimitiveValues<string>("repositories", Repositories);
            writer.WriteEnumValue<global::GitHub.EnterpriseCloud.Enterprises.Item.Apps.Organizations.Item.Installations.InstallationsPostRequestBody_repository_selection>("repository_selection", RepositorySelection);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
