// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.RetentionLimit;
using GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.StorageLimit;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organization_-id}\actions\cache
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CacheRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The retentionLimit property</summary>
        public global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.RetentionLimit.RetentionLimitRequestBuilder RetentionLimit
        {
            get => new global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.RetentionLimit.RetentionLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storageLimit property</summary>
        public global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.StorageLimit.StorageLimitRequestBuilder StorageLimit
        {
            get => new global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.StorageLimit.StorageLimitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.CacheRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CacheRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization_%2Did}/actions/cache", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Organizations.Item.Actions.Cache.CacheRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CacheRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization_%2Did}/actions/cache", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
