// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\innersource-vulnerabilities\sync\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.innersourceVulnerabilities.sync.status.item collection</summary>
        /// <param name="position">The unique identifier of the sync job.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("job_id", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.Item.WithJob_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities/sync/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.InnersourceVulnerabilities.Sync.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/innersource-vulnerabilities/sync/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
