// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.CodeScanning;
using GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.Dependabot;
using GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.SecretScanning;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner-id}\{repo-id}\dismissal-requests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DismissalRequestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The codeScanning property</summary>
        public global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.CodeScanning.CodeScanningRequestBuilder CodeScanning
        {
            get => new global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.CodeScanning.CodeScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dependabot property</summary>
        public global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.Dependabot.DependabotRequestBuilder Dependabot
        {
            get => new global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.Dependabot.DependabotRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The secretScanning property</summary>
        public global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.SecretScanning.SecretScanningRequestBuilder SecretScanning
        {
            get => new global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.SecretScanning.SecretScanningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.DismissalRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DismissalRequestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/dismissal-requests", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Repos.Item.Item.DismissalRequests.DismissalRequestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DismissalRequestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner%2Did}/{repo%2Did}/dismissal-requests", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
