// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JobsPostRequestBody_deployments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier for the deployment represented by the new record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentName { get; set; }
#nullable restore
#else
        public string DeploymentName { get; set; }
#endif
        /// <summary>The hex encoded digest of the artifact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Digest { get; set; }
#nullable restore
#else
        public string Digest { get; set; }
#endif
        /// <summary>The name of the GitHub repository associated with the artifact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GithubRepository { get; set; }
#nullable restore
#else
        public string GithubRepository { get; set; }
#endif
        /// <summary>The name of the artifact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A list of runtime risks associated with the deployment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_runtime_risks?>? RuntimeRisks { get; set; }
#nullable restore
#else
        public List<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_runtime_risks?> RuntimeRisks { get; set; }
#endif
        /// <summary>The deployment status of the artifact.</summary>
        public global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_status? Status { get; set; }
        /// <summary>Key-value pairs to tag the deployment record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_tags? Tags { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_tags Tags { get; set; }
#endif
        /// <summary>The artifact version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments"/> and sets the default values.
        /// </summary>
        public JobsPostRequestBody_deployments()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_status.Deployed;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deployment_name", n => { DeploymentName = n.GetStringValue(); } },
                { "digest", n => { Digest = n.GetStringValue(); } },
                { "github_repository", n => { GithubRepository = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "runtime_risks", n => { RuntimeRisks = n.GetCollectionOfEnumValues<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_runtime_risks>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_status>(); } },
                { "tags", n => { Tags = n.GetObjectValue<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_tags>(global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_tags.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("deployment_name", DeploymentName);
            writer.WriteStringValue("digest", Digest);
            writer.WriteStringValue("github_repository", GithubRepository);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfEnumValues<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_runtime_risks>("runtime_risks", RuntimeRisks);
            writer.WriteEnumValue<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_status>("status", Status);
            writer.WriteObjectValue<global::GitHub.Api.Orgs.Item.Artifacts.Metadata.DeploymentRecord.Cluster.Item.Jobs.JobsPostRequestBody_deployments_tags>("tags", Tags);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
