// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHub.Api.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::GitHub.Api.Models.AddedToProjectIssueEvent"/>, <see cref="global::GitHub.Api.Models.AssignedIssueEvent"/>, <see cref="global::GitHub.Api.Models.BlockedByAddedIssueEvent"/>, <see cref="global::GitHub.Api.Models.BlockedByRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.BlockingAddedIssueEvent"/>, <see cref="global::GitHub.Api.Models.BlockingRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.ConvertedNoteToIssueIssueEvent"/>, <see cref="global::GitHub.Api.Models.DemilestonedIssueEvent"/>, <see cref="global::GitHub.Api.Models.IssueTypeAddedIssueEvent"/>, <see cref="global::GitHub.Api.Models.IssueTypeChangedIssueEvent"/>, <see cref="global::GitHub.Api.Models.IssueTypeRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.LabeledIssueEvent"/>, <see cref="global::GitHub.Api.Models.LockedIssueEvent"/>, <see cref="global::GitHub.Api.Models.MilestonedIssueEvent"/>, <see cref="global::GitHub.Api.Models.MovedColumnInProjectIssueEvent"/>, <see cref="global::GitHub.Api.Models.ParentIssueAddedIssueEvent"/>, <see cref="global::GitHub.Api.Models.ParentIssueRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.RemovedFromProjectIssueEvent"/>, <see cref="global::GitHub.Api.Models.RenamedIssueEvent"/>, <see cref="global::GitHub.Api.Models.ReviewDismissedIssueEvent"/>, <see cref="global::GitHub.Api.Models.ReviewRequestedIssueEvent"/>, <see cref="global::GitHub.Api.Models.ReviewRequestRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.SubIssueAddedIssueEvent"/>, <see cref="global::GitHub.Api.Models.SubIssueRemovedIssueEvent"/>, <see cref="global::GitHub.Api.Models.UnassignedIssueEvent"/>, <see cref="global::GitHub.Api.Models.UnlabeledIssueEvent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IssueEventForIssue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.AddedToProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.AddedToProjectIssueEvent? AddedToProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.AddedToProjectIssueEvent AddedToProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.AssignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.AssignedIssueEvent? AssignedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.AssignedIssueEvent AssignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.BlockedByAddedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.BlockedByAddedIssueEvent? BlockedByAddedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.BlockedByAddedIssueEvent BlockedByAddedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.BlockedByRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.BlockedByRemovedIssueEvent? BlockedByRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.BlockedByRemovedIssueEvent BlockedByRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.BlockingAddedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.BlockingAddedIssueEvent? BlockingAddedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.BlockingAddedIssueEvent BlockingAddedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.BlockingRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.BlockingRemovedIssueEvent? BlockingRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.BlockingRemovedIssueEvent BlockingRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ConvertedNoteToIssueIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ConvertedNoteToIssueIssueEvent? ConvertedNoteToIssueIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ConvertedNoteToIssueIssueEvent ConvertedNoteToIssueIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.DemilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.DemilestonedIssueEvent? DemilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.DemilestonedIssueEvent DemilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.IssueTypeAddedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.IssueTypeAddedIssueEvent? IssueTypeAddedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.IssueTypeAddedIssueEvent IssueTypeAddedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.IssueTypeChangedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.IssueTypeChangedIssueEvent? IssueTypeChangedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.IssueTypeChangedIssueEvent IssueTypeChangedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.IssueTypeRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.IssueTypeRemovedIssueEvent? IssueTypeRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.IssueTypeRemovedIssueEvent IssueTypeRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.LabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.LabeledIssueEvent? LabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.LabeledIssueEvent LabeledIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.LockedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.LockedIssueEvent? LockedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.LockedIssueEvent LockedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.MilestonedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.MilestonedIssueEvent? MilestonedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.MilestonedIssueEvent MilestonedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.MovedColumnInProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.MovedColumnInProjectIssueEvent? MovedColumnInProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.MovedColumnInProjectIssueEvent MovedColumnInProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ParentIssueAddedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ParentIssueAddedIssueEvent? ParentIssueAddedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ParentIssueAddedIssueEvent ParentIssueAddedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ParentIssueRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ParentIssueRemovedIssueEvent? ParentIssueRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ParentIssueRemovedIssueEvent ParentIssueRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.RemovedFromProjectIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.RemovedFromProjectIssueEvent? RemovedFromProjectIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.RemovedFromProjectIssueEvent RemovedFromProjectIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.RenamedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.RenamedIssueEvent? RenamedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.RenamedIssueEvent RenamedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ReviewDismissedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ReviewDismissedIssueEvent? ReviewDismissedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ReviewDismissedIssueEvent ReviewDismissedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ReviewRequestedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ReviewRequestedIssueEvent? ReviewRequestedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ReviewRequestedIssueEvent ReviewRequestedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.ReviewRequestRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.ReviewRequestRemovedIssueEvent? ReviewRequestRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.ReviewRequestRemovedIssueEvent ReviewRequestRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.SubIssueAddedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.SubIssueAddedIssueEvent? SubIssueAddedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.SubIssueAddedIssueEvent SubIssueAddedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.SubIssueRemovedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.SubIssueRemovedIssueEvent? SubIssueRemovedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.SubIssueRemovedIssueEvent SubIssueRemovedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.UnassignedIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.UnassignedIssueEvent? UnassignedIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.UnassignedIssueEvent UnassignedIssueEvent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::GitHub.Api.Models.UnlabeledIssueEvent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHub.Api.Models.UnlabeledIssueEvent? UnlabeledIssueEvent { get; set; }
#nullable restore
#else
        public global::GitHub.Api.Models.UnlabeledIssueEvent UnlabeledIssueEvent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Api.Models.IssueEventForIssue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHub.Api.Models.IssueEventForIssue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::GitHub.Api.Models.IssueEventForIssue();
            result.AddedToProjectIssueEvent = new global::GitHub.Api.Models.AddedToProjectIssueEvent();
            result.AssignedIssueEvent = new global::GitHub.Api.Models.AssignedIssueEvent();
            result.BlockedByAddedIssueEvent = new global::GitHub.Api.Models.BlockedByAddedIssueEvent();
            result.BlockedByRemovedIssueEvent = new global::GitHub.Api.Models.BlockedByRemovedIssueEvent();
            result.BlockingAddedIssueEvent = new global::GitHub.Api.Models.BlockingAddedIssueEvent();
            result.BlockingRemovedIssueEvent = new global::GitHub.Api.Models.BlockingRemovedIssueEvent();
            result.ConvertedNoteToIssueIssueEvent = new global::GitHub.Api.Models.ConvertedNoteToIssueIssueEvent();
            result.DemilestonedIssueEvent = new global::GitHub.Api.Models.DemilestonedIssueEvent();
            result.IssueTypeAddedIssueEvent = new global::GitHub.Api.Models.IssueTypeAddedIssueEvent();
            result.IssueTypeChangedIssueEvent = new global::GitHub.Api.Models.IssueTypeChangedIssueEvent();
            result.IssueTypeRemovedIssueEvent = new global::GitHub.Api.Models.IssueTypeRemovedIssueEvent();
            result.LabeledIssueEvent = new global::GitHub.Api.Models.LabeledIssueEvent();
            result.LockedIssueEvent = new global::GitHub.Api.Models.LockedIssueEvent();
            result.MilestonedIssueEvent = new global::GitHub.Api.Models.MilestonedIssueEvent();
            result.MovedColumnInProjectIssueEvent = new global::GitHub.Api.Models.MovedColumnInProjectIssueEvent();
            result.ParentIssueAddedIssueEvent = new global::GitHub.Api.Models.ParentIssueAddedIssueEvent();
            result.ParentIssueRemovedIssueEvent = new global::GitHub.Api.Models.ParentIssueRemovedIssueEvent();
            result.RemovedFromProjectIssueEvent = new global::GitHub.Api.Models.RemovedFromProjectIssueEvent();
            result.RenamedIssueEvent = new global::GitHub.Api.Models.RenamedIssueEvent();
            result.ReviewDismissedIssueEvent = new global::GitHub.Api.Models.ReviewDismissedIssueEvent();
            result.ReviewRequestedIssueEvent = new global::GitHub.Api.Models.ReviewRequestedIssueEvent();
            result.ReviewRequestRemovedIssueEvent = new global::GitHub.Api.Models.ReviewRequestRemovedIssueEvent();
            result.SubIssueAddedIssueEvent = new global::GitHub.Api.Models.SubIssueAddedIssueEvent();
            result.SubIssueRemovedIssueEvent = new global::GitHub.Api.Models.SubIssueRemovedIssueEvent();
            result.UnassignedIssueEvent = new global::GitHub.Api.Models.UnassignedIssueEvent();
            result.UnlabeledIssueEvent = new global::GitHub.Api.Models.UnlabeledIssueEvent();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AddedToProjectIssueEvent != null || AssignedIssueEvent != null || BlockedByAddedIssueEvent != null || BlockedByRemovedIssueEvent != null || BlockingAddedIssueEvent != null || BlockingRemovedIssueEvent != null || ConvertedNoteToIssueIssueEvent != null || DemilestonedIssueEvent != null || IssueTypeAddedIssueEvent != null || IssueTypeChangedIssueEvent != null || IssueTypeRemovedIssueEvent != null || LabeledIssueEvent != null || LockedIssueEvent != null || MilestonedIssueEvent != null || MovedColumnInProjectIssueEvent != null || ParentIssueAddedIssueEvent != null || ParentIssueRemovedIssueEvent != null || RemovedFromProjectIssueEvent != null || RenamedIssueEvent != null || ReviewDismissedIssueEvent != null || ReviewRequestedIssueEvent != null || ReviewRequestRemovedIssueEvent != null || SubIssueAddedIssueEvent != null || SubIssueRemovedIssueEvent != null || UnassignedIssueEvent != null || UnlabeledIssueEvent != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AddedToProjectIssueEvent, AssignedIssueEvent, BlockedByAddedIssueEvent, BlockedByRemovedIssueEvent, BlockingAddedIssueEvent, BlockingRemovedIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, IssueTypeAddedIssueEvent, IssueTypeChangedIssueEvent, IssueTypeRemovedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, ParentIssueAddedIssueEvent, ParentIssueRemovedIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, SubIssueAddedIssueEvent, SubIssueRemovedIssueEvent, UnassignedIssueEvent, UnlabeledIssueEvent);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::GitHub.Api.Models.AddedToProjectIssueEvent>(null, AddedToProjectIssueEvent, AssignedIssueEvent, BlockedByAddedIssueEvent, BlockedByRemovedIssueEvent, BlockingAddedIssueEvent, BlockingRemovedIssueEvent, ConvertedNoteToIssueIssueEvent, DemilestonedIssueEvent, IssueTypeAddedIssueEvent, IssueTypeChangedIssueEvent, IssueTypeRemovedIssueEvent, LabeledIssueEvent, LockedIssueEvent, MilestonedIssueEvent, MovedColumnInProjectIssueEvent, ParentIssueAddedIssueEvent, ParentIssueRemovedIssueEvent, RemovedFromProjectIssueEvent, RenamedIssueEvent, ReviewDismissedIssueEvent, ReviewRequestedIssueEvent, ReviewRequestRemovedIssueEvent, SubIssueAddedIssueEvent, SubIssueRemovedIssueEvent, UnassignedIssueEvent, UnlabeledIssueEvent);
        }
    }
}
#pragma warning restore CS0618
