// <auto-generated/>
#pragma warning disable CS0618
using GitHub.Api.Advisories;
using GitHub.Api.Agents;
using GitHub.Api.App;
using GitHub.Api.AppManifests;
using GitHub.Api.Applications;
using GitHub.Api.Apps;
using GitHub.Api.Assignments;
using GitHub.Api.Classrooms;
using GitHub.Api.Codes_of_conduct;
using GitHub.Api.Credentials;
using GitHub.Api.Emojis;
using GitHub.Api.Enterprises;
using GitHub.Api.Events;
using GitHub.Api.Feeds;
using GitHub.Api.Gists;
using GitHub.Api.Gitignore;
using GitHub.Api.Installation;
using GitHub.Api.Issues;
using GitHub.Api.Licenses;
using GitHub.Api.Markdown;
using GitHub.Api.Marketplace_listing;
using GitHub.Api.Meta;
using GitHub.Api.Models;
using GitHub.Api.Networks;
using GitHub.Api.Notifications;
using GitHub.Api.Octocat;
using GitHub.Api.Organizations;
using GitHub.Api.Orgs;
using GitHub.Api.Rate_limit;
using GitHub.Api.Repos;
using GitHub.Api.Repositories;
using GitHub.Api.Search;
using GitHub.Api.Teams;
using GitHub.Api.User;
using GitHub.Api.Users;
using GitHub.Api.Versions;
using GitHub.Api.Zen;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.Api
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GitHubApiClient : BaseRequestBuilder
    {
        /// <summary>The advisories property</summary>
        public global::GitHub.Api.Advisories.AdvisoriesRequestBuilder Advisories
        {
            get => new global::GitHub.Api.Advisories.AdvisoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The agents property</summary>
        public global::GitHub.Api.Agents.AgentsRequestBuilder Agents
        {
            get => new global::GitHub.Api.Agents.AgentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The app property</summary>
        public global::GitHub.Api.App.AppRequestBuilder App
        {
            get => new global::GitHub.Api.App.AppRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The applications property</summary>
        public global::GitHub.Api.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::GitHub.Api.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The appManifests property</summary>
        public global::GitHub.Api.AppManifests.AppManifestsRequestBuilder AppManifests
        {
            get => new global::GitHub.Api.AppManifests.AppManifestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apps property</summary>
        public global::GitHub.Api.Apps.AppsRequestBuilder Apps
        {
            get => new global::GitHub.Api.Apps.AppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The assignments property</summary>
        public global::GitHub.Api.Assignments.AssignmentsRequestBuilder Assignments
        {
            get => new global::GitHub.Api.Assignments.AssignmentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The classrooms property</summary>
        public global::GitHub.Api.Classrooms.ClassroomsRequestBuilder Classrooms
        {
            get => new global::GitHub.Api.Classrooms.ClassroomsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The codes_of_conduct property</summary>
        public global::GitHub.Api.Codes_of_conduct.Codes_of_conductRequestBuilder Codes_of_conduct
        {
            get => new global::GitHub.Api.Codes_of_conduct.Codes_of_conductRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The credentials property</summary>
        public global::GitHub.Api.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::GitHub.Api.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The emojis property</summary>
        public global::GitHub.Api.Emojis.EmojisRequestBuilder Emojis
        {
            get => new global::GitHub.Api.Emojis.EmojisRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enterprises property</summary>
        public global::GitHub.Api.Enterprises.EnterprisesRequestBuilder Enterprises
        {
            get => new global::GitHub.Api.Enterprises.EnterprisesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::GitHub.Api.Events.EventsRequestBuilder Events
        {
            get => new global::GitHub.Api.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The feeds property</summary>
        public global::GitHub.Api.Feeds.FeedsRequestBuilder Feeds
        {
            get => new global::GitHub.Api.Feeds.FeedsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gists property</summary>
        public global::GitHub.Api.Gists.GistsRequestBuilder Gists
        {
            get => new global::GitHub.Api.Gists.GistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gitignore property</summary>
        public global::GitHub.Api.Gitignore.GitignoreRequestBuilder Gitignore
        {
            get => new global::GitHub.Api.Gitignore.GitignoreRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The installation property</summary>
        public global::GitHub.Api.Installation.InstallationRequestBuilder Installation
        {
            get => new global::GitHub.Api.Installation.InstallationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issues property</summary>
        public global::GitHub.Api.Issues.IssuesRequestBuilder Issues
        {
            get => new global::GitHub.Api.Issues.IssuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The licenses property</summary>
        public global::GitHub.Api.Licenses.LicensesRequestBuilder Licenses
        {
            get => new global::GitHub.Api.Licenses.LicensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The markdown property</summary>
        public global::GitHub.Api.Markdown.MarkdownRequestBuilder Markdown
        {
            get => new global::GitHub.Api.Markdown.MarkdownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The marketplace_listing property</summary>
        public global::GitHub.Api.Marketplace_listing.Marketplace_listingRequestBuilder Marketplace_listing
        {
            get => new global::GitHub.Api.Marketplace_listing.Marketplace_listingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meta property</summary>
        public global::GitHub.Api.Meta.MetaRequestBuilder Meta
        {
            get => new global::GitHub.Api.Meta.MetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The networks property</summary>
        public global::GitHub.Api.Networks.NetworksRequestBuilder Networks
        {
            get => new global::GitHub.Api.Networks.NetworksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::GitHub.Api.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::GitHub.Api.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The octocat property</summary>
        public global::GitHub.Api.Octocat.OctocatRequestBuilder Octocat
        {
            get => new global::GitHub.Api.Octocat.OctocatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizations property</summary>
        public global::GitHub.Api.Organizations.OrganizationsRequestBuilder Organizations
        {
            get => new global::GitHub.Api.Organizations.OrganizationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orgs property</summary>
        public global::GitHub.Api.Orgs.OrgsRequestBuilder Orgs
        {
            get => new global::GitHub.Api.Orgs.OrgsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rate_limit property</summary>
        public global::GitHub.Api.Rate_limit.Rate_limitRequestBuilder Rate_limit
        {
            get => new global::GitHub.Api.Rate_limit.Rate_limitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repos property</summary>
        public global::GitHub.Api.Repos.ReposRequestBuilder Repos
        {
            get => new global::GitHub.Api.Repos.ReposRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repositories property</summary>
        public global::GitHub.Api.Repositories.RepositoriesRequestBuilder Repositories
        {
            get => new global::GitHub.Api.Repositories.RepositoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::GitHub.Api.Search.SearchRequestBuilder Search
        {
            get => new global::GitHub.Api.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::GitHub.Api.Teams.TeamsRequestBuilder Teams
        {
            get => new global::GitHub.Api.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::GitHub.Api.User.UserRequestBuilder User
        {
            get => new global::GitHub.Api.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::GitHub.Api.Users.UsersRequestBuilder Users
        {
            get => new global::GitHub.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The versions property</summary>
        public global::GitHub.Api.Versions.VersionsRequestBuilder Versions
        {
            get => new global::GitHub.Api.Versions.VersionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zen property</summary>
        public global::GitHub.Api.Zen.ZenRequestBuilder Zen
        {
            get => new global::GitHub.Api.Zen.ZenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.Api.GitHubApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GitHubApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.github.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
        /// <summary>
        /// Get Hypermedia links to resources accessible in GitHub&apos;s REST API
        /// API method documentation <see href="https://docs.github.com/rest/meta/meta#github-api-root" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.Api.Models.Root"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.Api.Models.Root?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.Api.Models.Root> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::GitHub.Api.Models.Root>(requestInfo, global::GitHub.Api.Models.Root.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Hypermedia links to resources accessible in GitHub&apos;s REST API
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GitHubApiClientGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
