// <auto-generated/>
#pragma warning disable CS0618
using GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item;
using GitHub.EnterpriseCloud.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports
{
    /// <summary>
    /// Builds and executes requests for operations under \enterprises\{enterprise}\settings\billing\reports
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReportsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.settings.billing.reports.item collection</summary>
        /// <param name="position">The unique identifier (UUID) for the usage report export.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder"/></returns>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("report_id", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the GitHub.EnterpriseCloud.enterprises.item.settings.billing.reports.item collection</summary>
        /// <param name="position">The unique identifier (UUID) for the usage report export.</param>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("report_id", position);
                return new global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.Item.WithReport_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.ReportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing/reports", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.ReportsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReportsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/enterprises/{enterprise}/settings/billing/reports", rawUrl)
        {
        }
        /// <summary>
        /// Lists all usage report exports for an enterprise. The authenticated user must be an enterprise admin or billing manager.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/billing/usage-reports#list-usage-report-exports" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Models.UsageReportExportList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 500 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.UsageReportExportList503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Models.UsageReportExportList?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Models.UsageReportExportList> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "500", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "503", global::GitHub.EnterpriseCloud.Models.UsageReportExportList503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Models.UsageReportExportList>(requestInfo, global::GitHub.EnterpriseCloud.Models.UsageReportExportList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiates the generation of a usage report export for an enterprise. The report will be processed asynchronouslyand can be downloaded once completed. The authenticated user must be an enterprise admin or billing manager.
        /// API method documentation <see href="https://docs.github.com/enterprise-cloud@latest/rest/billing/usage-reports#create-a-usage-report-export" />
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Models.UsageReportExport"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 400 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 401 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 403 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 404 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.BasicError">When receiving a 500 status code</exception>
        /// <exception cref="global::GitHub.EnterpriseCloud.Models.UsageReportExport503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::GitHub.EnterpriseCloud.Models.UsageReportExport?> PostAsync(global::GitHub.EnterpriseCloud.Models.UsageReportExportRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::GitHub.EnterpriseCloud.Models.UsageReportExport> PostAsync(global::GitHub.EnterpriseCloud.Models.UsageReportExportRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "401", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "403", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "404", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "500", global::GitHub.EnterpriseCloud.Models.BasicError.CreateFromDiscriminatorValue },
                { "503", global::GitHub.EnterpriseCloud.Models.UsageReportExport503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::GitHub.EnterpriseCloud.Models.UsageReportExport>(requestInfo, global::GitHub.EnterpriseCloud.Models.UsageReportExport.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists all usage report exports for an enterprise. The authenticated user must be an enterprise admin or billing manager.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Initiates the generation of a usage report export for an enterprise. The report will be processed asynchronouslyand can be downloaded once completed. The authenticated user must be an enterprise admin or billing manager.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::GitHub.EnterpriseCloud.Models.UsageReportExportRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::GitHub.EnterpriseCloud.Models.UsageReportExportRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.ReportsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.ReportsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::GitHub.EnterpriseCloud.Enterprises.Item.Settings.Billing.Reports.ReportsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReportsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReportsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
